version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /home/username/mysqldatabase:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: somedb
      MYSQL_USER: someuser
      MYSQL_PASSWORD: someuserpassword