spring:
  application:
    name: blog-service
  active:
    profile: dev
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:myblog
    username: sa
    password: sa
    driverClassName: org.h2.Driver
server:
  port: 8010
management:
  endpoints:
    web:
      exposure:
        include: info, httptrace, metrics, health, routes
